language: generic
os: osx
osx_image: xcode6.4
install:
- sudo -E sh ./Scripts/install.sh
script:
- sudo -E sh ./Scripts/build.sh
after_success:
- sudo -E sh ./Scripts/post_build.sh
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: games-by-moonlight
  skip_cleanup: true
  on:
    branch: tool/9